-- MySQL Script generated by MySQL Workbench
-- Thu Jun  3 13:29:12 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Point_RDV`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Point_RDV` (
  `idPoint_RDV` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NULL,
  `Latitude` FLOAT(10,5) NULL,
  `Longitude` FLOAT(10,5) NULL,
  `Adresse` VARCHAR(45) NULL,
  `Ville` VARCHAR(45) NULL,
  `Point_Image` VARCHAR(255) NULL,
  `is_Confirme` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`idPoint_RDV`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Covoitureur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Covoitureur` (
  `idCovoitureur` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NULL,
  `Prenom` VARCHAR(45) NULL,
  `Utilisateur_Image` VARCHAR(255) NULL,
  `Num_Telephone` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `Mot_De_Passe` VARCHAR(255) NULL,
  `Nbr_Alveoles` INT NULL,
  `is_Confirme` TINYINT NULL DEFAULT 0,
  `is_Webmaster` TINYINT NULL,
  `idPoint_RDV` INT NOT NULL,
  PRIMARY KEY (`idCovoitureur`),
  INDEX `fk_Covoitureur_Point1_idx` (`idPoint_RDV` ASC),
  CONSTRAINT `fk_Covoitureur_Point1`
    FOREIGN KEY (`idPoint_RDV`)
    REFERENCES `mydb`.`Point_RDV` (`idPoint_RDV`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Voiture`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Voiture` (
  `idVoiture` INT NOT NULL AUTO_INCREMENT,
  `Modele` VARCHAR(45) NULL,
  `Marque` VARCHAR(45) NULL,
  `Annee` YEAR NULL,
  `Couleur` VARCHAR(45) NULL,
  `Nbr_Place` INT NULL,
  `Voiture_Image` VARCHAR(255) NULL,
  `is_Favoris` TINYINT NULL DEFAULT 0,
  `idCovoitureur` INT NOT NULL,
  PRIMARY KEY (`idVoiture`),
  INDEX `fk_Voiture_Covoitureur1_idx` (`idCovoitureur` ASC),
  CONSTRAINT `fk_Voiture_Covoitureur1`
    FOREIGN KEY (`idCovoitureur`)
    REFERENCES `mydb`.`Covoitureur` (`idCovoitureur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ligne`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ligne` (
  `idLigne` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NULL,
  `Nbr_Points` INT NULL,
  PRIMARY KEY (`idLigne`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Covoiturage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Covoiturage` (
  `idCovoiturage` INT NOT NULL AUTO_INCREMENT,
  `Jour` VARCHAR(45) NULL,
  `Heure` TIME NULL,
  `is_Depart_Lycee` TINYINT NULL,
  `idLigne` INT NOT NULL,
  PRIMARY KEY (`idCovoiturage`),
  INDEX `fk_Covoiturage_Ligne1_idx` (`idLigne` ASC),
  CONSTRAINT `fk_Covoiturage_Ligne1`
    FOREIGN KEY (`idLigne`)
    REFERENCES `mydb`.`Ligne` (`idLigne`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Participation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Participation` (
  `idParticipation` INT NOT NULL AUTO_INCREMENT,
  `is_Conducteur` TINYINT NULL,
  `Date` DATETIME NULL,
  `is_Valide_Systeme` TINYINT NULL,
  `is_Invalide_Webmaster` TINYINT NULL,
  `Kilometrage` INT NULL,
  `idCovoitureur` INT NOT NULL,
  `idCovoiturage` INT NOT NULL,
  PRIMARY KEY (`idParticipation`),
  INDEX `fk_Participation_Utilisateur1_idx` (`idCovoitureur` ASC),
  INDEX `fk_Participation_Covoiturage1_idx` (`idCovoiturage` ASC),
  CONSTRAINT `fk_Participation_Utilisateur1`
    FOREIGN KEY (`idCovoitureur`)
    REFERENCES `mydb`.`Covoitureur` (`idCovoitureur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Participation_Covoiturage1`
    FOREIGN KEY (`idCovoiturage`)
    REFERENCES `mydb`.`Covoiturage` (`idCovoiturage`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Etape`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Etape` (
  `idEtape` INT NOT NULL AUTO_INCREMENT,
  `Duree` TIME NULL,
  `Kilometrage` INT NULL,
  `idPoint_RDV_A` INT NOT NULL,
  `idPoint_RDV_B` INT NOT NULL,
  `idVoiture` INT NOT NULL,
  `idParticipation` INT NOT NULL,
  PRIMARY KEY (`idEtape`),
  INDEX `fk_Etape_Point1_idx` (`idPoint_RDV_A` ASC),
  INDEX `fk_Etape_Point2_idx` (`idPoint_RDV_B` ASC),
  INDEX `fk_Etape_Voiture1_idx` (`idVoiture` ASC),
  INDEX `fk_Etape_Participation1_idx` (`idParticipation` ASC),
  CONSTRAINT `fk_Etape_Point1`
    FOREIGN KEY (`idPoint_RDV_A`)
    REFERENCES `mydb`.`Point_RDV` (`idPoint_RDV`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Etape_Point2`
    FOREIGN KEY (`idPoint_RDV_B`)
    REFERENCES `mydb`.`Point_RDV` (`idPoint_RDV`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Etape_Voiture1`
    FOREIGN KEY (`idVoiture`)
    REFERENCES `mydb`.`Voiture` (`idVoiture`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Etape_Participation1`
    FOREIGN KEY (`idParticipation`)
    REFERENCES `mydb`.`Participation` (`idParticipation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Composition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Composition` (
  `idComposition` INT NOT NULL AUTO_INCREMENT,
  `Rang` INT NULL,
  `idPoint_RDV` INT NOT NULL,
  `idLigne` INT NOT NULL,
  PRIMARY KEY (`idComposition`),
  INDEX `fk_Composition_Point1_idx` (`idPoint_RDV` ASC),
  INDEX `fk_Composition_Trajet1_idx` (`idLigne` ASC),
  CONSTRAINT `fk_Composition_Point1`
    FOREIGN KEY (`idPoint_RDV`)
    REFERENCES `mydb`.`Point_RDV` (`idPoint_RDV`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Composition_Trajet1`
    FOREIGN KEY (`idLigne`)
    REFERENCES `mydb`.`Ligne` (`idLigne`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Indisponibilite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Indisponibilite` (
  `idIndisponibilite` INT NOT NULL AUTO_INCREMENT,
  `Debut_Fermeture` DATE NULL,
  `Fin_Fermeture` DATE NULL,
  `Motif_Fermeture` VARCHAR(45) NULL,
  PRIMARY KEY (`idIndisponibilite`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Inscription`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Inscription` (
  `idInscription` INT NOT NULL AUTO_INCREMENT,
  `idCovoitureur` INT NOT NULL,
  `idCovoiturage` INT NOT NULL,
  `Date_Depart` DATE NULL,
  `Semaine` VARCHAR(1) NULL,
  `is_Unique` TINYINT NULL,
  `is_Depart_Lycee` TINYINT NULL,
  `Jour_Semaine` VARCHAR(45) NULL,
  `Heure_Arrivee` TIME NULL,
  PRIMARY KEY (`idInscription`),
  INDEX `fk_Inscription_Covoitureur1_idx` (`idCovoitureur` ASC),
  INDEX `fk_Inscription_Covoiturage1_idx` (`idCovoiturage` ASC),
  CONSTRAINT `fk_Inscription_Covoitureur1`
    FOREIGN KEY (`idCovoitureur`)
    REFERENCES `mydb`.`Covoitureur` (`idCovoitureur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Inscription_Covoiturage1`
    FOREIGN KEY (`idCovoiturage`)
    REFERENCES `mydb`.`Covoiturage` (`idCovoiturage`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Token`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Token` (
  `idToken` INT NOT NULL AUTO_INCREMENT,
  `Content` VARCHAR(255) NULL,
  `Date_Creation` DATETIME NULL,
  `Date_Fin` DATETIME NULL,
  `idCovoitureur` INT NOT NULL,
  PRIMARY KEY (`idToken`),
  INDEX `fk_Token_Covoitureur1_idx` (`idCovoitureur` ASC),
  CONSTRAINT `fk_Token_Covoitureur1`
    FOREIGN KEY (`idCovoitureur`)
    REFERENCES `mydb`.`Covoitureur` (`idCovoitureur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
